server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jap:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true


#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo  -- if want to store data in DB in a file