server:
  port: 8082
logging:
  level:
    root: debug
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create-drop
  h2:
    console.enabled: true


#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo  -- if want to store data in DB in a file
